version: 2.1

orbs:
  maven: circleci/maven@1.0.3

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: cmd cd to C:/Program Files/Java/jdk-14.0.2/lib/security/cacerts
          command: cd C:/Program Files/Java/jdk-14.0.2/lib/security/cacerts
      - run:
          name: use keytool
          command: keytool -import -trustcacerts -file "certpath\certname.cer" -alias "cert_alias" -keystore "%JAVA_HOME%"/jre/lib/security/cacerts
      - run:
          mvn test